# Generated by Django 2.0 on 2019-04-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190321_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='builder',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
